version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-2 | docker login --username AWS --password-stdin 873873309630.dkr.ecr.ap-south-2.amazonaws.com
      - REPOSITORY_URI=873873309630.dkr.ecr.ap-south-2.amazonaws.com/brain-tasks-app
      - IMAGE_TAG=v1

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing deployment file...
      - kubectl set image deployment/brain-app brain-app=$REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - deployment.yaml
    - service.yaml
